Refactored the entire code base lol
unixporn-dots/unixporn-dots.github.io pull request #35
Opened 2022-07-21 16:46 UTC by mahancoder

In this PR, I've refactored the entire JavsScript codebase. I made everything object-oriented and just made everything make more sense. We also have global contexts now.
This should give you guys a good headstart for adding new features

I still believe that the CSS and HTML codebases are really messed up, and I might fix them later in another PR.
There is also an inconsistency in naming conventions, among function names, variables, and also element Id/Class names.

This PR does not include ManorSailor's preview image button, since I forked the main branch, so I suggest you guys just merge this into the new branch and add the preview button manually, adhering to the new template of cards and image preview window.

Have fun!

2022-07-21 20:15 UTC, ArmoredVortex approved these changes
These are really amazing changes. Thanks a lot for this.
I did read through all the changes (although quickly than i should've) and did try it out locally and wasn't able to find any sort of issues with both the UI and functionality.
Good Job!

2022-07-22 03:59 UTC, mahancoder commented
You're welcome, if you anytime found any issues, please let me know and I will try to fix them

2022-07-22 07:16 UTC, ManorSailor requested changes
Amazing work! The code-base looks really clean now & it will be easier to add features in it in the future. I have reviewed the changes which I could understand & everything seems fine, except one thing, image preview on mobile screen is broken, its nothing too big. You renamed `imgViewer` class to `img-viewer` but the class name in media-query was left unchanged :)

Its a small fix. Other than this, I found nothing else. And, the codebase is clean now. Great work!

2022-07-22 07:25 UTC, ManorSailor approved these changes

2022-07-22 07:28 UTC, merged